[project]
name = "gpt-realtime-simple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "numpy>=2.3.3",
    "sounddevice>=0.5.2",
    "websockets>=15.0.1",
]
